### ISSUE TITLE
undefined method `new' for ... ActiveSupport::TimeZone

### ISSUE THREAD

**Issue by scottwillson** [mojombo/chronic#208]
Apologies for not offering up a patch + test case. After upgrading to 0.10.0, I see:

```
undefined method `new' for (GMT-08:00) Pacific Time (US & Canada):ActiveSupport::TimeZone
chronic (0.10.0) lib/chronic.rb:141:in `construct'
chronic (0.10.0) lib/chronic/repeaters/repeater_day_portion.rb:74:in `this' 
chronic (0.10.0) lib/chronic/handlers.rb:524:in `get_anchor'
```

I am using Rails and setting `Chronic.time_class = Time.zone` per the README.
